import type { AppTheme } from "@/lib/DynamicStyles";

export const defaultTheme: AppTheme = {
  layout: "default",
  variables: {
    light: {
      primaryColor: "#2563eb",
      secondaryColor: "#1e293b",
      tertiaryColor: "#f9fafb",
      topBarTextColor: "#f9fafb",
      SidebarTextColor: "#f9fafb",
      buttonColor: "#2563eb",
      buttonHoverColor: "#1d4ed8",
      backgroundImage: "none",
      backgroundColor: "#ffffff",
      textColor: "#111827",
      sectionColor: "#f9fafb",
      sectionTransparency: "1",
      borderColor: "#d1d5db",
      mutedTextColor: "#6b7280",
      headingColor: "#111827",
      linkColor: "#2563eb",
      errorColor: "#dc2626",
      successColor: "#16a34a",
      warningColor: "#f59e0b",
      infoColor: "#0ea5e9",
      badgeBgColor: "#e0f2fe",
      badgeTextColor: "#0369a1",
      tableHeadBgColor: "#f1f1f1",
      tableHeadTextColor: "#333333",
      tableBodyTextColor: "#444444",
      pageButtonBgColor: "#f5f5f5",
      pageButtonBorderColor: "#cccccc",
      blockquoteBorderColor: "#d1d5db",
      blockquoteTextColor: "#6b7280",
      cardShadow: "0 1px 3px rgba(0, 0, 0, 0.1)",
      modalShadow: "0 10px 25px rgba(0, 0, 0, 0.2)",
      menuShadow: "0 4px 6px rgba(0,0,0,0.1)",
      navbarShadow: "0 2px 4px rgba(0,0,0,0.1)",
    },
    dark: {
      primaryColor: "#3b82f6",
      secondaryColor: "#0f172a",
      tertiaryColor: "#1e293b",
      topBarTextColor: "#f9fafb",
      SidebarTextColor: "#f9fafb",
      buttonColor: "#3b82f6",
      buttonHoverColor: "#2563eb",
      backgroundImage: "none",
      backgroundColor: "#0f172a",
      textColor: "#f9fafb",
      sectionColor: "#1e293b",
      sectionTransparency: "0.85",
      borderColor: "#334155",
      mutedTextColor: "#94a3b8",
      headingColor: "#f1f5f9",
      linkColor: "#3b82f6",
      errorColor: "#f87171",
      successColor: "#4ade80",
      warningColor: "#fbbf24",
      infoColor: "#38bdf8",
      badgeBgColor: "#1e40af",
      badgeTextColor: "#dbeafe",
      tableHeadBgColor: "#1e293b",
      tableHeadTextColor: "#e2e8f0",
      tableBodyTextColor: "#cbd5e1",
      pageButtonBgColor: "#334155",
      pageButtonBorderColor: "#475569",
      blockquoteBorderColor: "#475569",
      blockquoteTextColor: "#94a3b8",
      cardShadow: "0 1px 3px rgba(0, 0, 0, 0.6)",
      modalShadow: "0 10px 25px rgba(0, 0, 0, 0.7)",
      menuShadow: "0 4px 6px rgba(0,0,0,0.6)",
      navbarShadow: "0 2px 4px rgba(0,0,0,0.6)",
    },
  },
  componentStyles: {
    Button: {
      backgroundColor: "{{buttonColor}}",
      color: "{{backgroundColor}}",
      border: "none",
      borderRadius: "0.375rem",
      padding: "0.5rem 1rem",
      fontSize: "1rem",
      cursor: "pointer",
      hover: {
        color: "{{buttonHoverColor}}",
      },
      transition: "background-color 0.3s ease",
    },
    TextInput: {
      width: "100%",
      padding: "0.5rem",
      border: "1px solid {{borderColor}}",
      borderRadius: "0.375rem",
      fontSize: "1rem",
      lineHeight: "1.5",
      outline: "none",
      transition: "border-color 0.2s ease",
      justifyContent: "center",
      alignContent: "center",
      alignItems: "center",
      textAlign: "center",
    },
    EmailInput: {
      width: "100%",
      padding: "0.5rem",
      border: "1px solid {{borderColor}}",
      borderRadius: "0.375rem",
      fontSize: "1rem",
      lineHeight: "1.5",
      outline: "none",
      transition: "border-color 0.2s ease",
      justifyContent: "center",
      alignContent: "center",
      alignItems: "center",
      textAlign: "center",
    },
    PasswordInput: {
      width: "100%",
      padding: "0.5rem",
      border: "1px solid {{borderColor}}",
      borderRadius: "0.375rem",
      fontSize: "1rem",
      lineHeight: "1.5",
      outline: "none",
      transition: "border-color 0.2s ease",
      justifyContent: "center",
      alignContent: "center",
      alignItems: "center",
      textAlign: "center",
    },
    NumberInput: {
      width: "100%",
      padding: "0.5rem",
      border: "1px solid {{borderColor}}",
      borderRadius: "0.375rem",
      fontSize: "1rem",
      lineHeight: "1.5",
      outline: "none",
      MozAppearance: "textfield",
      justifyContent: "center",
      alignContent: "center",
      alignItems: "center",
      textAlign: "center",
    },
    CheckboxInput: {
      width: "1rem",
      height: "1rem",
      accentColor: "{{primaryColor}}",
      cursor: "pointer",
      justifyContent: "center",
      alignContent: "center",
      alignItems: "center",
      textAlign: "center",
    },
    RadioInput: {
      width: "1rem",
      height: "1rem",
      accentColor: "{{primaryColor}}",
      cursor: "pointer",
      justifyContent: "center",
      alignContent: "center",
      alignItems: "center",
      textAlign: "center",
    },
    FileInput: {
      padding: "0.25rem 0.5rem",
      border: "1px solid {{borderColor}}",
      borderRadius: "0.375rem",
      backgroundColor: "{{tertiaryColor}}",
      fontSize: "0.875rem",
      cursor: "pointer",
      justifyContent: "center",
      alignContent: "center",
      alignItems: "center",
      textAlign: "center",
    },
    DateInput: {
      width: "100%",
      padding: "0.5rem",
      border: "1px solid {{borderColor}}",
      borderRadius: "0.375rem",
      fontSize: "1rem",
      lineHeight: "1.5",
      outline: "none",
      justifyContent: "center",
      alignContent: "center",
      alignItems: "center",
      textAlign: "center",
    },
    TextArea: {
      width: "100%",
      padding: "0.5rem",
      minHeight: "5rem",
      border: "1px solid {{borderColor}}",
      borderRadius: "0.375rem",
      fontSize: "1rem",
      lineHeight: "1.5",
      outline: "none",
      resize: "vertical",
      transition: "border-color 0.2s ease",
      justifyContent: "center",
      alignContent: "center",
      alignItems: "center",
      textAlign: "center",
    },
    SelectInput: {
      width: "100%",
      padding: "0.5rem",
      border: "1px solid {{borderColor}}",
      borderRadius: "0.375rem",
      fontSize: "1rem",
      lineHeight: "1.5",
      backgroundColor: "{{backgroundColor}}",
      outline: "none",
      appearance: "none",
      backgroundImage:
        "url('data:image/svg+xml;utf8,<svg fill='%23666' height='20' viewBox='0 0 24 24' width='20' xmlns='http://www.w3.org/2000/svg'><path d='M7 10l5 5 5-5z'/></svg>')",
      backgroundRepeat: "no-repeat",
      backgroundPosition: "right 0.5rem center",
      backgroundSize: "1rem",
      transition: "border-color 0.2s ease",
      justifyContent: "center",
      alignContent: "center",
      alignItems: "center",
      textAlign: "center",
    },
    RangeInput: {
      width: "100%",
      cursor: "pointer",
      appearance: "none",
      height: "0.5rem",
      borderRadius: "0.25rem",
      backgroundColor: "#e5e7eb",
      outline: "none",
      transition: "background 0.2s ease",
      justifyContent: "center",
      alignContent: "center",
      alignItems: "center",
      textAlign: "center",
    },
    ColorInput: {
      width: "3rem",
      height: "3rem",
      border: "none",
      padding: "0",
      background: "none",
      cursor: "pointer",
      justifyContent: "center",
      alignContent: "center",
      alignItems: "center",
      textAlign: "center",
    },
    FormGroup: {
      display: "flex",
      flexDirection: "column",
      gap: "0.5rem",
      marginBottom: "1rem",
      width: "100%",
    },
    ErrorText: {
      marginTop: "0.25rem",
      fontSize: "0.875rem",
      color: "{{errorColor}}",
    },
    FieldWrapper: {
      display: "flex",
      flexDirection: "column",
      gap: "0.25rem",
      width: "100%",
    },
    AudioMedia: {
      width: "100%",
      maxWidth: "100%",
      outline: "none",
      display: "block",
      alignItems: "center",
      justifyContent: "center",
      textAlign: "center",
    },
    VideoMedia: {
      width: "100%",
      height: "auto",
      maxWidth: "100%",
      display: "block",
      objectFit: "cover",
      borderRadius: "8px",
      alignItems: "center",
      justifyContent: "center",
      textAlign: "center",
    },
    ImageMedia: {
      width: "100%",
      height: "auto",
      maxWidth: "100%",
      display: "block",
      objectFit: "cover",
      borderRadius: "8px",
      alignItems: "center",
      justifyContent: "center",
      textAlign: "center",
    },
    Card: {
      backgroundColor: "{{backgroundColor}}",
      borderRadius: "0.5rem",
      padding: "1rem",
      boxShadow: "{{cardShadow}}",
      alignItems: "center",
      justifyContent: "center",
      textAlign: "center",
      display: "flex",
      flexDirection: "column",
    },
    CardHeader: {
      padding: "1rem",
      borderBottom: "1px solid {{borderColor}}",
      fontWeight: "600",
      fontSize: "1.125rem",
      backgroundColor: "{{tertiaryColor}}",
      alignItems: "center",
      justifyContent: "center",
      textAlign: "center",
      width: "100%",
    },
    CardFooter: {
      padding: "1rem",
      borderTop: "1px solid {{borderColor}}",
      display: "flex",
      justifyContent: "flex-end",
      backgroundColor: "{{tertiaryColor}}",
      alignItems: "center",
      textAlign: "center",
      width: "100%",
      height: "3rem",
    },
    CardContent: {
      padding: "1rem",
      display: "flex",
      flexDirection: "column",
      gap: "0.5rem",
      backgroundColor: "{{backgroundColor}}",
      alignItems: "center",
      justifyContent: "center",
      textAlign: "center",
      width: "100%",
      height: "auto",
      flex: 1,
    },
    Modal: {
      backgroundColor: "{{backgroundColor}}",
      padding: "2rem",
      borderRadius: "0.5rem",
      width: "90%",
      maxWidth: "500px",
      boxShadow: "{{modalShadow}}",
      alignItems: "center",
      justifyContent: "center",
      textAlign: "center",
      // New properties (non-breaking additions)
      position: "fixed",
      top: "50%",
      left: "50%",
      transform: "translate(-50%, -50%)",
      zIndex: 10001, // stays on top of all other content
    },
    ModalBackdrop: {
      position: "fixed",
      top: 0,
      left: 0,
      width: "100vw",
      height: "100vh",
      backgroundColor: "rgba(0, 0, 0, 0.4)", // dim layer
      backdropFilter: "blur(8px)", // blur background
      zIndex: 999, // sits behind the modal
    },
    Text: {
      fontSize: "1rem",
      color: "{{textColor}}",
    },
    Label: {
      fontSize: "0.875rem",
      fontWeight: "500",
      marginBottom: "0.25rem",
      color: "{{mutedTextColor}}",
      justifyContent: "center",
      alignContent: "center",
      alignItems: "center",
      textAlign: "center",
    },
    Checkbox: {
      width: "1rem",
      height: "1rem",
      accentColor: "{{primaryColor}}",
      justifyContent: "center",
      alignContent: "center",
      alignItems: "center",
      textAlign: "center",
    },
    Radio: {
      width: "1rem",
      height: "1rem",
      accentColor: "{{primaryColor}}",
      justifyContent: "center",
      alignContent: "center",
      alignItems: "center",
      textAlign: "center",
    },
    Select: {
      padding: "0.5rem",
      borderRadius: "0.375rem",
      border: "1px solid {{borderColor}}",
      backgroundColor: "{{backgroundColor}}",
      fontSize: "1rem",
      justifyContent: "center",
      alignContent: "center",
      alignItems: "center",
      textAlign: "center",
    },
    Table: {
      width: "100%",
      borderCollapse: "collapse",
      justifyContent: "center",
      alignContent: "center",
      alignItems: "center",
      textAlign: "center",
    },
    TableRow: {
      borderBottom: "1px solid {{borderColor}}",
      justifyContent: "center",
      alignContent: "center",
      alignItems: "center",
      textAlign: "center",
      cursor: "default",
    },
    TableCell: {
      padding: "0.75rem",
      textAlign: "left",
      fontSize: "0.875rem",
      justifyContent: "center",
      alignContent: "center",
      alignItems: "center",
    },
    TableWrapper: {
      width: "100%",
      borderCollapse: "collapse",
    },
    PaginationWrapper: {
      marginTop: "1rem",
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
    },
    PageButton: {
      padding: "0.2rem 0.5rem",
      backgroundColor: "{{pageButtonBgColor}}",
      border: "1px solid {{pageButtonBorderColor}}",
      cursor: "pointer",
      borderRadius: "4px",
      hover: {
        color: "{{buttonHoverColor}}",
      },
      transition: "background 0.3s ease",
    },
    TableHead: {
      backgroundColor: "{{tableHeadBgColor}}",
      color: "{{tableHeadTextColor}}",
      fontWeight: "bold",
      fontSize: "1rem",
      textAlign: "center",
      borderBottom: "2px solid {{pageButtonBorderColor}}",
    },
    TableBody: {
      fontSize: "0.95rem",
      color: "{{tableBodyTextColor}}",
    },
    Heading: {
      fontSize: "1.25rem",
      fontWeight: "600",
      marginBottom: "0.5rem",
      color: "{{headingColor}}",
    },
    Heading1: {
      fontSize: "2.25rem",
      fontWeight: 700,
      margin: "1.5rem 0 1rem 0",
      color: "{{headingColor}}",
    },
    Heading2: {
      fontSize: "1.875rem",
      fontWeight: 600,
      margin: "1.25rem 0 1rem 0",
      color: "{{headingColor}}",
    },
    Heading3: {
      fontSize: "1.5rem",
      fontWeight: 600,
      margin: "1rem 0",
      color: "{{headingColor}}",
    },
    Heading4: {
      fontSize: "1.25rem",
      fontWeight: "600",
      margin: "0.75rem 0",
      color: "{{headingColor}}",
    },
    Heading5: {
      fontSize: "1rem",
      fontWeight: "600",
      margin: "0.5rem 0",
      color: "{{mutedTextColor}}",
    },
    Heading6: {
      fontSize: "0.875rem",
      fontWeight: "500",
      margin: "0.5rem 0",
      color: "{{mutedTextColor}}",
    },
    Link: {
      color: "{{linkColor}}",
      textDecoration: "none",
      cursor: "pointer",
      display: "flex",
      textAlign: "center",
      justifyContent: "center",
      alignItems: "center",
    },
    Span: {
      color: "inherit",
      paddingLeft: "0.5rem",
      paddingRight: "0.5rem",
    },
    Avatar: {
      width: "2.5rem",
      height: "2.5rem",
      borderRadius: "9999px",
      objectFit: "cover",
    },
    Badge: {
      backgroundColor: "{{badgeBgColor}}",
      color: "{{badgeTextColor}}",
      fontSize: "0.75rem",
      padding: "0.25rem 0.5rem",
      borderRadius: "9999px",
    },
    Paragraph: {
      fontSize: "1rem",
      lineHeight: "1.6",
      margin: "0 0 1rem 0",
      color: "{{mutedTextColor}}",
    },
    Form: {
      display: "flex",
      flexDirection: "column",
      gap: "1rem",
      padding: "1.5rem",
      border: "1px solid {{borderColor}}",
      borderRadius: "0.5rem",
      backgroundColor: "{{backgroundColor}}",
      maxWidth: "600px",
      width: "100%",
      boxShadow: "{{cardShadow}}",
      alignContent: "center",
      alignItems: "center",
      textAlign: "center",
      justifyContent: "center",
    },
    ul: {
      paddingLeft: "1.5rem",
      marginBottom: "1.25rem",
      listStyleType: "disc",
    },
    ol: {
      paddingLeft: "1.5rem",
      marginBottom: "1.25rem",
      listStyleType: "decimal",
    },
    li: {
      marginBottom: "0.5rem",
      fontSize: "1rem",
      color: "{{mutedTextColor}}",
    },
    blockquote: {
      borderLeft: "4px solid {{blockquoteBorderColor}}",
      paddingLeft: "1.25rem",
      color: "{{blockquoteTextColor}}",
      fontStyle: "italic",
      margin: "1.5rem 0",
    },
    Section: {
      padding: "2rem 1.5rem",
      margin: "2rem 0",
      backgroundColor: "{{sectionColor}}",
      borderRadius: "0.5rem",
      boxShadow: "0 1px 3px rgba(0, 0, 0, {{sectionTransparency}})",
      border: "1px solid {{borderColor}}",
      display: "block",
      alignItems: "center",
      justifyContent: "center",
      alignContent: "center",
      textAlign: "center",
    },
    PageContainer: {
      display: "flex",
      flexDirection: "column",
      minHeight: "100vh",
      width: "100%",
      backgroundColor: "{{sectionColor}}",
      color: "{{textColor}}",
      overflow: "hidden",
    },
    Topbar: {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      backgroundColor: "{{secondaryColor}}",
      color: "{{topBarTextColor}}",
      height: "3.5rem",
      boxShadow: "{{navbarShadow}}",
      position: "fixed",
      top: "0",
      width: "100%",
      zIndex: 1001,
      flexShrink: 0,
      textAlign: "center",
      overflow: "hidden",
    },
    Sidebar: {
      display: "flex",
      flexDirection: "column",
      width: "16rem",
      backgroundColor: "{{secondaryColor}}",
      height: "100%",
      padding: "1rem",
      borderRight: "1px solid {{borderColor}}",
      position: "fixed",
      color: "{{SidebarTextColor}}",
      marginTop: "3.5rem",
      visibility: "visible",
      transition: "transform 0.3s ease-in-out",
    },
    Main: {
      backgroundColor: "{{backgroundColor}}",
      overflowX: "hidden",
      display: "flex",
      color: "inherit",
      flex: 1,
      overflowY: "auto",
    },
    Info: {
      padding: "2rem",
      backgroundColor: "{{backgroundColor}}",
      width: "100%",
      overflowX: "hidden",
      overflowY: "hidden",
      color: "inherit",
      flex: 1,
    },
    Footer: {
      display: "flex",
      flexDirection: "row",
      gap: "1rem",
      alignItems: "center",
      justifyContent: "center",
      padding: "2rem 1rem",
      backgroundColor: "{{secondaryColor}}",
      borderTop: "1px solid {{borderColor}}",
      color: "{{mutedTextColor}}",
      fontSize: "0.875rem",
      lineHeight: "1.5",
      textAlign: "center",
      height: "3.5rem",
      position: "sticky",
      bottom: "0",
      width: "100%",
    },
    Grid: {
      display: "grid",
      gap: "1rem",
      gridTemplateColumns: "repeat(auto-fit, minmax(320px, 1fr))",
      gridAutoRows: "minmax(300px, auto)",
      justifyItems: "stretch",
      alignItems: "stretch",
      width: "100%",
    },
    Menu: {
      display: "flex",
      flexDirection: "column",
      backgroundColor: "transparent",
      borderRadius: "0.375rem",
      boxShadow: "0 2px 10px rgba(0,0,0,0.05)",
      padding: "0.5rem 0",
      color: "inherit",
      cursor: "pointer",
      position: "relative",
    },
    MenuList: {
      listStyle: "none",
      margin: "0",
      color: "inherit",
      position: "absolute",
      top: "100%",
      right: 0,
      backgroundColor: "{{backgroundColor}}",
      boxShadow: "{{menuShadow}}",
      borderRadius: "0.375rem",
      marginTop: "0.5rem",
      padding: "0",
      minWidth: "10rem",
      zIndex: 1001,
      visibility: "visible",
    },
    MenuItem: {
      padding: "0.5rem 1rem",
      fontSize: "0.875rem",
      color: "{{mutedTextColor}}",
      cursor: "pointer",
      transition: "background-color 0.2s ease-in-out",
      whiteSpace: "nowrap",
    },
    SideNavigation: {
      display: "flex",
      flexDirection: "column",
      gap: "0.5rem",
      padding: "1rem 0",
      color: "inherit",
    },
    NavigationDrawer: {
      position: "fixed",
      top: "0",
      left: "0",
      height: "100%",
      width: "16rem",
      backgroundColor: "{{backgroundColor}}",
      borderRight: "1px solid {{borderColor}}",
      boxShadow: "2px 0 6px rgba(0,0,0,0.1)",
      zIndex: 1050,
      padding: "1rem",
      transform: "translateX(-100%)",
      color: "inherit",
    },
    MenuNavbar: {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      backgroundColor: "transparent",
      padding: "0.75rem",
      color: "{{topBarTextColor}}",
      height: "3.5rem",
      boxShadow: "{{navbarShadow}}",
      position: "fixed",
      top: 0,
      right: 0,
      width: "auto",
      overflow: "none",
      zIndex: 1000,
      flexShrink: 0,
      flex: 1,
    },
    Navbar: {
      display: "flex",
      alignItems: "right",
      justifyContent: "flex-end",
      backgroundColor: "transparent",
      padding: "0.75rem",
      color: "{{topBarTextColor}}",
      height: "3.5rem",
      boxShadow: "{{navbarShadow}}",
      position: "relative",
      top: 0,
      right: 0,
      width: "auto",
      overflow: "none",
      zIndex: 1000,
      flexShrink: 0,
      flex: 1,
    },
    NavItem: {
      padding: "0.5rem",
      color: "inherit",
    },
    Logo: {
      backgroundColor: "transparent",
      width: "auto",
    },
    ThemeModeSwitch: {
      backgroundColor: "transparent",
      color: "{{topbarColor}}",
      borderRadius: "2rem",
      marginLeft: "2rem",
      marginRight: "2rem",
      cursor: "pointer",
    },
  },
};
