import type { AppTheme } from "@/lib/DynamicStyles";

export const defaultTheme: AppTheme = {
  componentStyles: {
    Button: {
      backgroundColor: "#2563eb",
      color: "#ffffff",
      border: "none",
      borderRadius: "0.375rem",
      padding: "0.5rem 1rem",
      fontSize: "1rem",
      cursor: "pointer",
      transition: "background-color 0.3s ease",
    },

    // Form Items
    TextInput: {
      width: "100%",
      padding: "0.5rem",
      border: "1px solid #d1d5db", // Tailwind gray-300
      borderRadius: "0.375rem", // rounded-md
      fontSize: "1rem",
      lineHeight: "1.5",
      outline: "none",
      transition: "border-color 0.2s ease",
      justifyContent: "center",
      alignContent: "center",
      alignItems: "center",
      textAlign: "center",
    },
    EmailInput: {
      width: "100%",
      padding: "0.5rem",
      border: "1px solid #d1d5db",
      borderRadius: "0.375rem",
      fontSize: "1rem",
      lineHeight: "1.5",
      outline: "none",
      transition: "border-color 0.2s ease",
      justifyContent: "center",
      alignContent: "center",
      alignItems: "center",
      textAlign: "center",
    },
    PasswordInput: {
      width: "100%",
      padding: "0.5rem",
      border: "1px solid #d1d5db",
      borderRadius: "0.375rem",
      fontSize: "1rem",
      lineHeight: "1.5",
      outline: "none",
      transition: "border-color 0.2s ease",
      justifyContent: "center",
      alignContent: "center",
      alignItems: "center",
      textAlign: "center",
    },
    NumberInput: {
      width: "100%",
      padding: "0.5rem",
      border: "1px solid #d1d5db",
      borderRadius: "0.375rem",
      fontSize: "1rem",
      lineHeight: "1.5",
      outline: "none",
      MozAppearance: "textfield", // hide spinner in Firefox
      justifyContent: "center",
      alignContent: "center",
      alignItems: "center",
      textAlign: "center",
    },
    CheckboxInput: {
      width: "1rem",
      height: "1rem",
      accentColor: "#2563eb", // blue-600
      cursor: "pointer",
      justifyContent: "center",
      alignContent: "center",
      alignItems: "center",
      textAlign: "center",
    },
    RadioInput: {
      width: "1rem",
      height: "1rem",
      accentColor: "#2563eb",
      cursor: "pointer",
      justifyContent: "center",
      alignContent: "center",
      alignItems: "center",
      textAlign: "center",
    },
    FileInput: {
      padding: "0.25rem 0.5rem",
      border: "1px solid #d1d5db",
      borderRadius: "0.375rem",
      backgroundColor: "#f9fafb",
      fontSize: "0.875rem",
      cursor: "pointer",
      justifyContent: "center",
      alignContent: "center",
      alignItems: "center",
      textAlign: "center",
    },
    DateInput: {
      width: "100%",
      padding: "0.5rem",
      border: "1px solid #d1d5db",
      borderRadius: "0.375rem",
      fontSize: "1rem",
      lineHeight: "1.5",
      outline: "none",
      justifyContent: "center",
      alignContent: "center",
      alignItems: "center",
      textAlign: "center",
    },
    TextArea: {
      width: "100%",
      padding: "0.5rem",
      minHeight: "5rem",
      border: "1px solid #d1d5db", // gray-300
      borderRadius: "0.375rem", // rounded-md
      fontSize: "1rem",
      lineHeight: "1.5",
      outline: "none",
      resize: "vertical",
      transition: "border-color 0.2s ease",
      justifyContent: "center",
      alignContent: "center",
      alignItems: "center",
      textAlign: "center",
    },
    SelectInput: {
      width: "100%",
      padding: "0.5rem",
      border: "1px solid #d1d5db",
      borderRadius: "0.375rem",
      fontSize: "1rem",
      lineHeight: "1.5",
      backgroundColor: "#ffffff",
      outline: "none",
      appearance: "none", // removes default arrow
      backgroundImage:
        "url('data:image/svg+xml;utf8,<svg fill='%23666' height='20' viewBox='0 0 24 24' width='20' xmlns='http://www.w3.org/2000/svg'><path d='M7 10l5 5 5-5z'/></svg>')",
      backgroundRepeat: "no-repeat",
      backgroundPosition: "right 0.5rem center",
      backgroundSize: "1rem",
      transition: "border-color 0.2s ease",
      justifyContent: "center",
      alignContent: "center",
      alignItems: "center",
      textAlign: "center",
    },
    RangeInput: {
      width: "100%",
      cursor: "pointer",
      appearance: "none",
      height: "0.5rem",
      borderRadius: "0.25rem",
      backgroundColor: "#e5e7eb", // gray-200
      outline: "none",
      transition: "background 0.2s ease",
      justifyContent: "center",
      alignContent: "center",
      alignItems: "center",
      textAlign: "center",
    },
    ColorInput: {
      width: "3rem",
      height: "3rem",
      border: "none",
      padding: "0",
      background: "none",
      cursor: "pointer",
      justifyContent: "center",
      alignContent: "center",
      alignItems: "center",
      textAlign: "center",
    },
    FormGroup: {
      display: "flex",
      flexDirection: "column",
      gap: "0.5rem",
      marginBottom: "1rem",
      width: "100%",
    },
    ErrorText: {
      marginTop: "0.25rem",
      fontSize: "0.875rem",
      color: "#dc2626", // Red-600
    },
    FieldWrapper: {
      display: "flex",
      flexDirection: "column",
      gap: "0.25rem",
      width: "100%",
    },

    // Media
    AudioMedia: {
      width: "100%",
      maxWidth: "100%",
      outline: "none",
      display: "block",
      alignItems: "center",
      justifyContent: "center",
      textAlign: "center",
    },
    VideoMedia: {
      width: "100%",
      height: "auto",
      maxWidth: "100%",
      display: "block",
      objectFit: "cover",
      borderRadius: "8px",
      alignItems: "center",
      justifyContent: "center",
      textAlign: "center",
    },
    ImageMedia: {
      width: "100%",
      height: "auto",
      maxWidth: "100%",
      display: "block",
      objectFit: "cover",
      borderRadius: "8px",
      alignItems: "center",
      justifyContent: "center",
      textAlign: "center",
    },

    // General Items
    Card: {
      backgroundColor: "#ffffff",
      borderRadius: "0.5rem",
      padding: "1rem",
      boxShadow: "0 1px 3px rgba(0, 0, 0, 0.1)",
      alignItems: "center",
      justifyContent: "center",
      textAlign: "center",
      display: "flex",
      flexDirection: "column",
    },
    CardHeader: {
      padding: "1rem",
      borderBottom: "1px solid #e5e7eb",
      fontWeight: "600",
      fontSize: "1.125rem",
      backgroundColor: "#f9fafb",
      alignItems: "center",
      justifyContent: "center",
      textAlign: "center",
      width: "100%",
    },
    CardFooter: {
      padding: "1rem",
      borderTop: "1px solid #e5e7eb",
      display: "flex",
      justifyContent: "flex-end",
      backgroundColor: "#f9fafb",
      alignItems: "center",
      textAlign: "center",
      width: "100%",
      height: "3rem",
    },
    CardContent: {
      padding: "1rem",
      display: "flex",
      flexDirection: "column",
      gap: "0.5rem",
      backgroundColor: "#ffffff",
      alignItems: "center",
      justifyContent: "center",
      textAlign: "center",
      width: "100%",
      height: "auto",
      flex: 1,
    },
    Modal: {
      backgroundColor: "#ffffff",
      padding: "2rem",
      borderRadius: "0.5rem",
      width: "90%",
      maxWidth: "500px",
      boxShadow: "0 10px 25px rgba(0, 0, 0, 0.2)",
    },
    Text: {
      fontSize: "1rem",
      color: "#111827",
    },
    Label: {
      fontSize: "0.875rem",
      fontWeight: "500",
      marginBottom: "0.25rem",
      color: "#374151",
      justifyContent: "center",
      alignContent: "center",
      alignItems: "center",
      textAlign: "center",
    },
    Checkbox: {
      width: "1rem",
      height: "1rem",
      accentColor: "#2563eb",
      justifyContent: "center",
      alignContent: "center",
      alignItems: "center",
      textAlign: "center",
    },
    Radio: {
      width: "1rem",
      height: "1rem",
      accentColor: "#2563eb",
      justifyContent: "center",
      alignContent: "center",
      alignItems: "center",
      textAlign: "center",
    },
    Select: {
      padding: "0.5rem",
      borderRadius: "0.375rem",
      border: "1px solid #d1d5db",
      backgroundColor: "#ffffff",
      fontSize: "1rem",
      justifyContent: "center",
      alignContent: "center",
      alignItems: "center",
      textAlign: "center",
    },
    Table: {
      width: "100%",
      borderCollapse: "collapse",
      justifyContent: "center",
      alignContent: "center",
      alignItems: "center",
      textAlign: "center",
    },
    TableRow: {
      borderBottom: "1px solid #e5e7eb",
      justifyContent: "center",
      alignContent: "center",
      alignItems: "center",
      textAlign: "center",
      cursor: "default",
    },
    TableCell: {
      padding: "0.75rem",
      textAlign: "left",
      fontSize: "0.875rem",
      justifyContent: "center",
      alignContent: "center",
      alignItems: "center",
    },
    TableWrapper: {
      width: "100%",
      borderCollapse: "collapse",
    },
    PaginationWrapper: {
      marginTop: "1rem",
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
    },
    PageButton: {
      padding: "0.2rem 0.5rem",
      backgroundColor: "#f5f5f5",
      border: "1px solid #ccc",
      cursor: "pointer",
      borderRadius: "4px",
      transition: "background 0.3s ease",
    },
    TableHead: {
      backgroundColor: "#f1f1f1",
      color: "#333",
      fontWeight: "bold",
      fontSize: "1rem",
      textAlign: "center",
      borderBottom: "2px solid #ccc",
    },
    TableBody: {
      fontSize: "0.95rem",
      color: "#444",
    },
    Heading: {
      fontSize: "1.25rem",
      fontWeight: "600",
      marginBottom: "0.5rem",
      color: "#111827",
    },
    Heading1: {
      fontSize: "2.25rem",
      fontWeight: 700,
      margin: "1.5rem 0 1rem 0",
      color: "#111827",
    },

    Heading2: {
      fontSize: "1.875rem",
      fontWeight: 600,
      margin: "1.25rem 0 1rem 0",
      color: "#111827",
    },

    Heading3: {
      fontSize: "1.5rem",
      fontWeight: 600,
      margin: "1rem 0",
      color: "#1f2937",
    },

    Heading4: {
      fontSize: "1.25rem",
      fontWeight: 600,
      margin: "0.75rem 0",
      color: "#1f2937",
    },

    Heading5: {
      fontSize: "1rem",
      fontWeight: 600,
      margin: "0.5rem 0",
      color: "#374151",
    },

    Heading6: {
      fontSize: "0.875rem",
      fontWeight: 500,
      margin: "0.5rem 0",
      color: "#6b7280",
    },
    Link: {
      color: "#2563eb",
      textDecoration: "none",
      cursor: "pointer",
      display: "flex",
      textAlign: "center",
      justifyContent: "center",
      alignItems: "center",
    },
    Span: {
      color: "inherit",
      paddingLeft: "0.5rem",
      paddingRight: "0.5rem",
    },
    Avatar: {
      width: "2.5rem",
      height: "2.5rem",
      borderRadius: "9999px",
      objectFit: "cover",
    },
    Badge: {
      backgroundColor: "#e0f2fe",
      color: "#0369a1",
      fontSize: "0.75rem",
      padding: "0.25rem 0.5rem",
      borderRadius: "9999px",
    },
    Paragraph: {
      fontSize: "1rem",
      lineHeight: "1.6",
      margin: "0 0 1rem 0",
      color: "#374151",
    },
    Form: {
      display: "flex",
      flexDirection: "column",
      gap: "1rem",
      padding: "1.5rem",
      border: "1px solid #e5e7eb",
      borderRadius: "0.5rem",
      backgroundColor: "#ffffff",
      maxWidth: "600px",
      width: "100%",
      boxShadow: "0 1px 3px rgba(0, 0, 0, 0.1)",
      alignContent: "center",
      alignItems: "center",
      textAlign: "center",
      justifyContent: "center",
    },

    // 📋 Lists
    ul: {
      paddingLeft: "1.5rem",
      marginBottom: "1.25rem",
      listStyleType: "disc",
    },
    ol: {
      paddingLeft: "1.5rem",
      marginBottom: "1.25rem",
      listStyleType: "decimal",
    },
    li: {
      marginBottom: "0.5rem",
      fontSize: "1rem",
      color: "#374151",
    },

    // 💬 Quotes
    blockquote: {
      borderLeft: "4px solid #d1d5db",
      paddingLeft: "1.25rem",
      color: "#6b7280",
      fontStyle: "italic",
      margin: "1.5rem 0",
    },

    Section: {
      padding: "2rem 1.5rem",
      margin: "2rem 0",
      backgroundColor: "#f9fafb", // subtle background
      borderRadius: "0.5rem",
      boxShadow: "0 1px 3px rgba(0, 0, 0, 0.05)",
      border: "1px solid #e5e7eb",
      display: "block",
      alignItems: "center",
      justifyContent: "center",
      alignContent: "center",
      textAlign: "center",
    },

    // === Layout Components ===
    PageContainer: {
      display: "flex",
      flexDirection: "column",
      minHeight: "100vh",
      width: "100%",
      backgroundColor: "#f9fafb", // light background
      color: "#000000",
      overflow: "hidden",
    },

    Topbar: {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      backgroundColor: "#0f172a", // Gray-800
      color: "#f1f5f9",
      height: "3.5rem",
      boxShadow: "0 2px 4px rgba(0,0,0,0.1)",
      position: "fixed",
      top: "0",
      width: "100%",
      zIndex: 1001,
      flexShrink: 0,
      textAlign: "center",
      overflow: "hidden",
    },

    Sidebar: {
      display: "flex",
      flexDirection: "column",
      width: "16rem", // 256px
      backgroundColor: "#1e293b", // Gray-50
      height: "100%",
      padding: "1rem",
      borderRight: "1px solid #334155", // Gray-200
      position: "fixed",
      color: "#e2e8f0",
      marginTop: "3.5rem",
      visibility: "visible",
      transition: "transform 0.3s ease-in-out",
    },

    Main: {
      backgroundColor: "#ffffff",
      overflowX: "hidden",
      display: "flex",
      color: "inherit",
      flex: 1,
      overflowY: "auto",
    },

    Info: {
      padding: "2rem",
      backgroundColor: "#fefefe",
      width: "100%",
      overflowX: "hidden",
      overflowY: "hidden",
      color: "inherit",
      flex: 1,
    },

    Footer: {
      display: "flex",
      flexDirection: "row",
      gap: "1rem",
      alignItems: "center",
      justifyContent: "center",
      padding: "2rem 1rem",
      backgroundColor: "#0f172a",
      borderTop: "1px solid #1e293b",
      color: "#94a3b8",
      fontSize: "0.875rem",
      lineHeight: "1.5",
      textAlign: "center",
      height: "3.5rem",
      position: "sticky",
      bottom: "0",
      width: "100%",
    },
    Grid: {
      display: "grid",
      gap: "1rem",
      gridTemplateColumns: "repeat(auto-fit, minmax(320px, 1fr))",
      gridAutoRows: "minmax(300px, auto)",
      justifyItems: "stretch",
      alignItems: "stretch",
      width: "100%",
    },

    // === Navigation Components ===
    Menu: {
      display: "flex",
      flexDirection: "column",
      backgroundColor: "transparent",
      borderRadius: "0.375rem",
      boxShadow: "0 2px 10px rgba(0,0,0,0.05)",
      padding: "0.5rem 0",
      color: "inherit",
      cursor: "pointer",
      position: "relative",
    },

    MenuList: {
      listStyle: "none",
      margin: "0",
      color: "inherit",
      position: "absolute",
      top: "100%",
      right: 0,
      backgroundColor: "#ffffff",
      boxShadow: "0 4px 6px rgba(0,0,0,0.1)",
      borderRadius: "0.375rem",
      marginTop: "0.5rem",
      padding: "0",
      minWidth: "10rem",
      zIndex: 1001,
      visibility: "visible",
    },

    MenuItem: {
      padding: "0.5rem 1rem",
      fontSize: "0.875rem",
      color: "#374151", // Gray-700
      cursor: "pointer",
      transition: "background-color 0.2s ease-in-out",
      whiteSpace: "nowrap",
    },

    SideNavigation: {
      display: "flex",
      flexDirection: "column",
      gap: "0.5rem",
      padding: "1rem 0",
      color: "inherit",
    },

    NavigationDrawer: {
      position: "fixed",
      top: "0",
      left: "0",
      height: "100%",
      width: "16rem",
      backgroundColor: "#ffffff",
      borderRight: "1px solid #e5e7eb",
      boxShadow: "2px 0 6px rgba(0,0,0,0.1)",
      zIndex: 1050,
      padding: "1rem",
      transform: "translateX(-100%)",
      color: "inherit",
    },
    MenuNavbar: {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      backgroundColor: "transparent",
      padding: "0.75rem",
      color: "#ffffff",
      height: "3.5rem",
      boxShadow: "0 2px 4px rgba(0,0,0,0.1)",
      position: "fixed",
      top: 0,
      right: 0,
      width: "auto",
      overflow: "none",
      zIndex: 1000,
      flexShrink: 0,
      flex: 1,
    },
    Navbar: {
      display: "flex",
      alignItems: "right",
      justifyContent: "flex-end",
      backgroundColor: "transparent",
      padding: "0.75rem",
      color: "#ffffff",
      height: "3.5rem",
      boxShadow: "0 2px 4px rgba(0,0,0,0.1)",
      position: "relative",
      top: 0,
      right: 0,
      width: "auto",
      overflow: "none",
      zIndex: 1000,
      flexShrink: 0,
      flex: 1,
    },
    NavItem: {
      padding: "0.5rem",
    },
    Logo: {
      backgroundColor: "transparent",
      width: "auto",
    },
  },
};
