import type { Metadata } from "next";
import Link from "next/link";
import "../globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="h-dvh wh-full flex bg-slate-800 overflow-hidden">
          <aside className="h-full top-0 fixed w-14 z-50 bg-slate-800 text-center align-center justify-center overflow-hidden group p-1 hover:w-50">
            <Link
              className="text-center w-full cursor-pointer flex align-center"
              href="pageeditor"
            >
              <svg
                className="w-10 h-10 text-gray-800 dark:text-white"
                aria-hidden="true"
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                fill="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  fillRule="evenodd"
                  d="M11 4.717c-2.286-.58-4.16-.756-7.045-.71A1.99 1.99 0 0 0 2 6v11c0 1.133.934 2.022 2.044 2.007 2.759-.038 4.5.16 6.956.791V4.717Zm2 15.081c2.456-.631 4.198-.829 6.956-.791A2.013 2.013 0 0 0 22 16.999V6a1.99 1.99 0 0 0-1.955-1.993c-2.885-.046-4.76.13-7.045.71v15.081Z"
                  clipRule="evenodd"
                />
              </svg>
              <div className="align-center hidden group-hover:block p-2">
                Page Editor
              </div>
            </Link>
          </aside>
          <main className="h-full w-full bg-white text-black ml-14 overflow-auto">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
