// import {
//   PageContainer,
//   Sidebar,
//   Topbar,
//   Logo,
//   Main,
//   Info,
//   Footer,
//   Section,
//   Card,
//   CardContent,
//   CardHeader,
//   CardFooter,
//   Grid,
//   SideNavigation,
//   NavigationDrawer,
//   MenuNav,
//   Navbar,
//   NavItem,
//   Menu,
//   MenuList,
//   MenuItem,
//   TableWrapper,
//   PaginationWrapper,
//   PageButton,
//   TableHead,
//   TableBody,
//   TableRow,
//   TableData,
//   Table,
// } from "../components/LayoutComponents";

// import {
//   AudioMedia,
//   VideoMedia,
//   ImageMedia,
// } from "../components/MediaComponents";

// import {
//   Heading1,
//   Heading2,
//   Heading3,
//   Heading4,
//   Heading5,
//   Heading6,
//   Paragraph,
//   Span,
//   Button,
// } from "../components/GeneralComponents";

// import {
//   Form,
//   TextInput,
//   EmailInput,
//   PasswordInput,
//   NumberInput,
//   CheckboxInput,
//   RadioInput,
//   FileInput,
//   DateInput,
//   ErrorText,
//   FieldWrapper,
//   Label,
//   FormGroup,
//   RangeInput,
//   SelectInput,
//   TextArea,
// } from "../components/FormElements";

// export const AllComponentsMap = {
//   PageContainer,
//   Sidebar,
//   Topbar,
//   Logo,
//   Main,
//   Info,
//   Footer,
//   Section,
//   Card,
//   CardContent,
//   CardHeader,
//   CardFooter,
//   Grid,
//   SideNavigation,
//   NavigationDrawer,
//   MenuNav,
//   Navbar,
//   NavItem,
//   Menu,
//   MenuList,
//   MenuItem,
//   TableWrapper,
//   PaginationWrapper,
//   PageButton,
//   TableHead,
//   TableBody,
//   TableRow,
//   TableData,
//   Table,
//   AudioMedia,
//   VideoMedia,
//   ImageMedia,
//   Heading1,
//   Heading2,
//   Heading3,
//   Heading4,
//   Heading5,
//   Heading6,
//   Paragraph,
//   Span,
//   Button,
//   Form,
//   TextInput,
//   EmailInput,
//   PasswordInput,
//   NumberInput,
//   CheckboxInput,
//   RadioInput,
//   FileInput,
//   DateInput,
//   ErrorText,
//   FieldWrapper,
//   Label,
//   FormGroup,
//   RangeInput,
//   SelectInput,
//   TextArea,
// };
